### ISSUE TITLE
Got "not a supported wheel on this platform" error

### ISSUE THREAD

**Issue by hongta** [TomHeaven/tensorflow-osx-build#1]
Got following error:
```
tensorflow-1.4.0-cp27-cp27m-macosx_10_12_intel.whl is not a supported wheel on this platform.
```
OS: 10.12.6
pip: 9.0.1
CUDA:  8.0.83
cuDNN: 6.0
Python on Anaconda: 3.6

**Comment by TomHeaven** [comment]
This project is built for python 2.7, which osx contains itself in Python.framework. I suggest u to uninstall Anconda and retry or install and activate python 2.7 using anconda.
