### ISSUE TITLE
Building 1.14rc0

### ISSUE THREAD

**Issue by hoonkai** [TomHeaven/tensorflow-osx-build#12]
Hi

I was wondering if you've had the chance to try building [v1.14-rc0](https://github.com/tensorflow/tensorflow/tree/v1.14.0-rc0). I've been trying to build it with Bazel 0.24, but I keep running into the error:
```
external/local_config_cuda/cuda/BUILD:168:1: Executing genrule @local_config_cuda//cuda:cuda-include failed (Exit 1): bash failed: error executing command
...
/bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cp -rLf "/usr/local/cuda/include/." "bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include/" ')
Execution platform: @bazel_tools//platforms:host_platform
cp: the -H, -L, and -P options may not be specified with the -r option.
```

I could proceed by replacing `cp -r` with `cp -R` in the generated `BUILD` file, but then this error later gets in the way:

```
ERROR: /Volumes/Data/Projects/tensorflow-1.14/src/tensorflow/tensorflow/core/kernels/BUILD:1766:1: output 'tensorflow/core/kernels/_objs/gather_functor_gpu/gather_functor_gpu.cu.pic.o' was not created
```

Not sure if you have better luck?

Cheers

**Comment by TomHeaven** [comment]
I'll try building v1.14-rc0. But  v1.14-rc0 is a pre-release, I do not recommend you to use it.  In addition, building a pre-release is often more troublesome.

**Comment by TomHeaven** [comment]
I've found the cause. `cp` command of osx does not accept `rLf` as an argument. We need to update `third-party/gpus/cuda_configure.bazel`. Find the two lines
```
  cmd = \"""cp -rLf "%s/." "%s/" \""",
)""" % (name, "\n".join(outs), src_dir, out_dir)
```
and replace it with
```
cmd = \"""cp -r -f "%s/." "%s/" \""",
)""" % (name, "\n".join(outs), src_dir, out_dir)
```

Recompile TF and the problem should be solved.

**Comment by TomHeaven** [comment]
TF 1.14.0rc1 build is available at https://github.com/TomHeaven/tensorflow-osx-build/releases/tag/v1.14.0rc1_cu100.

**Comment by hoonkai** [comment]
@TomHeaven Thanks for that!
