### ISSUE TITLE
2.0.0b0 vs 2.0.0 - Import Error

### ISSUE THREAD

**Issue by dbarnes** [TomHeaven/tensorflow-osx-build#14]
Hi Tom,

Thanks for your effort putting these wheels together!

I managed to install and run the 2.0.0b0 release fine that was put up earlier this morning  but run into a fault with the 2.0.0 wheel you uploaded as below.

```
>>> import tensorflow as tf
[1]    43217 illegal hardware instruction  python
```

I will try and compile for myself with your updated instructions,  but I was wondering if there was a change in compile flags (maybe cpu optimisations) between these releases to track down what is causing this? 

I was also wondering if you were planning to look to compile OSX wheels for any of the other Tensorflow packages which are now available such as Tensorflow Addons (https://github.com/tensorflow/addons) ?

Thanks,

Dan

System
10.13.6 
2.7 GHz 12-Core Intel Xeon E5
CUDA 10.0
cuDNN 7.4

**Comment by TomHeaven** [comment]
Thanks for the feedback. 

I built 2.0.0b0 on a machine with Intel Xeon E5 CPU and 2.0.0 on a machine with Intel 8th generation CPU. The new generation CPU may use some new instructions which are not available on older CPUs. 

Maybe there are some build options which will increase the compatibility of the builds. But I still cannot find them now.  I'll simply re-build 2.0.0 on E5 CPU and update the release.

**Comment by dbarnes** [comment]
That would be great thank you. If I can do anything to help just let me know

**Comment by TomHeaven** [comment]
Release 2.0.0 is updated. Please check if the issue is solved.

**Comment by dbarnes** [comment]
That works great thank you.

With regards to the new additional packages (such as Tensorflow Addons https://github.com/tensorflow/addons) do you have any plans to try to build them for gpu on osx? If not please close this issue and Ill let you know when I get around to having a go if interested.

Cheers

**Comment by TomHeaven** [comment]
This no plan for addons at present.
