### ISSUE TITLE
tf v2.0.0.b1 request

### ISSUE THREAD

**Issue by wangyu1997** [TomHeaven/tensorflow-osx-build#15]
Hey Tom

Thank you for your effort. 
And I am using the tf2.0 and torch successfully.
But TF2.0 has some bugs that cannot autocomplete by IDE like import tensorflow.keras as K

Would You Please Tell Me How to build or install tensorflow-2.0.0-beta1 version on my computer?

thanks a lot.

**Comment by TomHeaven** [comment]
Follow the [tutorial for tf2.0](https://github.com/TomHeaven/tensorflow-osx-build/blob/master/build_tutorial_2.0.0.md) and the source patches are almost the some.
