### ISSUE TITLE
Can you support tensaflow2.2.0 of CUDA10.1？

### ISSUE THREAD

**Issue by Https443** [TomHeaven/tensorflow-osx-build#19]
可以编译支持CUDA10.1的tensonflow2.2.0吗？因为需要升级到了xcode10.1，然后就歇菜了。。。

**Comment by TomHeaven** [comment]
Here is what you want: https://github.com/TomHeaven/tensorflow-osx-build/releases/tag/v2.0.0_cu101_cudnn76

**Comment by Https443** [comment]
thanks!
