### ISSUE TITLE
[Question]: How you managed to get lc_version_min_macosx in the Mach-O

### ISSUE THREAD

**Issue by august25** [TomHeaven/tensorflow-osx-build#20]
Hi,

This isn't an issue, just a question on how you managed to get lc_version_min_macosx into the Mach-O. I've tried setting these options below, and even "export MACOSX_DEPLOYMENT_TARGET=10.12"

build --action_env PYTHON_BIN_PATH="/Users/myusername/.pyenv/versions/3.7.5/bin/python"
build --action_env PYTHON_LIB_PATH="/Users/myusername/.pyenv/versions/3.7.5/lib/python3.7/site-packages"
build --python_path="/Users/myusername/.pyenv/versions/3.7.5/bin/python"
build:xla --define with_xla_support=true
build --copt=-march=native
build --copt=-Wno-sign-compare
**build --copt=-mmacosx-version-min=10.12**
**build --linkopt="-mmacosx-version-min=10.12"**
build --host_copt=-march=native
**build --host_copt=-mmacosx-version-min=10.12**
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu,-nomac,-no_mac
test --build_tag_filters=-gpu,-nomac,-no_mac
build --action_env TF_CONFIGURE_IOS="0"
**build --action_env MACOSX_DEPLOYMENT_TARGET=10.12**

Could it be because using CUDA forces it to be signed differently? I'm trying to build a CPU only version with those Mach-O headers and your build is the only one I've found to contain it. Any help would be greatly appreciated. Thank you

**Comment by TomHeaven** [comment]
I didn't even notice "lc_version_min_macosx". If you want to build a CPU only version, simply follow this [guide](https://github.com/TomHeaven/tensorflow-osx-build/blob/master/build_tutorial_2.0.0.md) and set CUDA option off.
