### ISSUE TITLE
how to build tensorflow 2.3.0 on mac

### ISSUE THREAD

**Issue by llv22** [TomHeaven/tensorflow-osx-build#21]
@TomHeaven I can't find any patch for tensorflow 2.3.0, but there was indeed built tensorflow 2.3.0 in your release tag. Could you help me understand how I can manage to build tensorflow 2.3.0 on mac 10.13.6 cracked machine? Thanks a lot in advance

**Comment by TomHeaven** [comment]
You missed the release note, which tells you the source code for TF 2.3.0 is here: https://github.com/TomHeaven/tensorflow/releases

**Comment by llv22** [comment]
@TomHeaven can we use official version and add patch like before?

**Comment by llv22** [comment]
@TomHeaven one more question, on mac 13.6, with cuda 10.0 + cudnn v7.4.2.24 + nccl 2.6.4, xcode 9.4.1, can we use your 2.3.0 version to build out library? ^-^
