### ISSUE TITLE
楼主是否可以提供libtensorflow_cc.so以及tensorflow_framework.2.3.dylib?

### ISSUE THREAD

**Issue by jasonperhaps** [TomHeaven/tensorflow-osx-build#24]
您提供的编译的包安装可以完美运行，非常感谢博主的工作！然而，再利用tensorflow进行C++开发时，并没有dylib文件，楼主是否可以release出来 或者给一个编译教学呢

**Comment by TomHeaven** [comment]
在TF安装路径下是有动态库的，名字是：`_pywrap_tensorflow_internal.so`，默认安装路径是`/usr/local/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so`。

**Comment by jasonperhaps** [comment]
感谢楼主的回复，已顺利编译编写的cc文件
