### ISSUE TITLE
Do you pursue with tensorflow 2.7 on macOS 10.13.6

### ISSUE THREAD

**Issue by llv22** [TomHeaven/tensorflow-osx-build#25]
as title, curious about this.

**Comment by m416kar98k** [comment]
这是结束
tensorflow 将不再支持 cuda 10.x 和 xcode 10.x 
您可以在 jax 上继续您的项目或使用来自更高版本 os 的预编译包

**Comment by llv22** [comment]
@m416kar98k if you cracked it, the official announcement is just a straw that can be dropped away...

**Comment by hypersad** [comment]
code it before you said it

**Comment by llv22** [comment]
@TomHeaven some updates about cracking tensorflow 2.9 on macOS 10.13.6, CUDA 10.1, cudnn 7.6.3 via Xcode 10.1.
Recently I spent about 2 weeks to identify the root cause of why tensorflow 2.9 can't work on the aforementioned environment.

Besides the normal compilation issues, the major show-blocker lies at the bazel building system, because on macOS 10.13.6 the ARG_MAX is about 262144, which is far less than the setting on 10.14. But we can crack bazel system for its default linking behavior in https://github.com/llv22/bazel-macOS-10.13.6/blob/r5.2.1/src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkAction.java.  Basically it merges object files to intermediate objects, then further link them together, which can workaround to avoid the issue over the pre-setting  of input arguments.

1. The built tensorflow 2.9 libraries compatible with your environment are uploaded here: https://github.com/llv22/tensorflow-macOS-cuda/releases/tag/mac10.13.6-cuda10.1-2.9.0
2. For building the source code on your own,
* you can download the cracked bazel version from https://github.com/llv22/bazel-macOS-10.13.6/releases/tag/5.2.1
* Download https://github.com/llv22/tensorflow-macOS-cuda and build from scratch
* Download https://github.com/llv22/tensorflow-io-macOS and build io, which requires tf2.9.0

**Comment by TomHeaven** [comment]
Great work!

**Comment by llv22** [comment]
@TomHeaven actually there is still one minor feature to enable auto-switch between GPU and CPU mode, esp. for GPU tensorflow installer. But not a big issue.
