### ISSUE TITLE
TensorFlow 1.10 with CUDA 9.2

### ISSUE THREAD

**Issue by rickeycarter** [TomHeaven/tensorflow-osx-build#3]
Have you had success compiling TF 1.10 against CUDA 9.2? Does it compile cleanly from source or are there patches that need to be developed?

**Comment by TomHeaven** [comment]
I'll compile a binary for CUDA 9.2.

Official team of Tensorflow announced that they had dropped support for Mac OS with Nvidia GPUs. So the source need to be patched before it can be compiled on Mac OS.

I'll try to add patch files to the repo, but it will take some time.

**Comment by rickeycarter** [comment]
It's okay.  I'll give it a go.  I just noticed you didn't have a 9.2 so I wasn't sure if there was an issues against that version. I'm still running a self compiled 1.5 w/GPU support but it looks like I need to move to CUDA 9.2 soon so I'm planning the next steps.

**Comment by TomHeaven** [comment]
I've compiled tf 1.10 against CUDA 9.2. However, the build does not work properly. It keeps reporting `CUDA OUT OF MEMORY ERROR` and the test program does not generate correct results.

In fact, tf 1.8 build against CUDA 9.2 also report errors about `CANNOT FIND GPU WITH ID 0`. Yet the results seem to be correct so I neglect the errors.

My suggestion is do NOT move to CUDA 9.2 at present.

**Comment by TomHeaven** [comment]
Build instructions are also added to the master branch. I'm closing the issue.
