### ISSUE TITLE
Can you provide build instructions from official tensorflow sources ?

### ISSUE THREAD

**Issue by bpresles** [TomHeaven/tensorflow-osx-build#4]
Hello Tom,

Nice work on that builds. But I'd like to make personal builds. I've tried following those instructions: https://gist.github.com/Willian-Zhang/088e017774536880bd425178b46b8c17, so using the provided patch on this page (https://gist.github.com/Willian-Zhang/088e017774536880bd425178b46b8c17#file-xtensorflow17macos-patch).

The build goes well, as well as the installation of the resulting whl, but when I start to compute something with Tensorflow, I get a segfault.
I also tried without applying the patch at all, but then it doesn't build.

I'm curious of what patches you applied to the original sources to get it working fully?

Thank you.
Regards

**Comment by TomHeaven** [comment]
I'll try to add patch files to the repo, but it will take some time because usually every release of Tensorflow requires a different patch.

**Comment by TomHeaven** [comment]
Build instructions have been added to the master branch. Go to the following link:
https://github.com/TomHeaven/tensorflow-osx-build/blob/master/build_instructions_1.10.md
