### ISSUE TITLE
undeclared inclusion(s) in rule '//tensorflow/core/kernels:nccl_kernels'

### ISSUE THREAD

**Issue by riverflow** [TomHeaven/tensorflow-osx-build#9]
Can you please build your tensorflows with bazel option '--copt=-march=westmere'? I can't build  and I can't execute your tensorflows for my Mac Pro 5,1.

In compile process, I got this error many times

ERROR: undeclared inclusion(s) in rule '//tensorflow/core/kernels:nccl_kernels':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/nccl_ops.cc':
'third_party/nccl/nccl.h'
tensorflow/core/kernels/nccl_ops.cc:189:15: warning: private field 'reduction_op_' is not used [-Wunused-private-field]
ncclRedOp_t reduction_op_;
^
1 warning generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build

When I install your tensorflow version, got 'Illegal instruction: 4' when importing tensorflow

I did ‘git checkout r1.12’ and use python 3.6 (in anaconda)

Sorry for the inconvenience

**Comment by TomHeaven** [comment]
Try adding a build flag  `--config=nonccl` as follows
```
bazel build --config=opt --config=nonccl  //tensorflow/tools/pip_package:build_pip_package
```

**Comment by TomHeaven** [comment]
Closing due to long time no response. Reopen if needed.
